name: Build Android APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java Environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build Mobile Game Natively
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential ccache git ffmpeg libgstreamer1.0-dev unzip zip libtool pkg-config autoconf automake libffi-dev libssl-dev shared-mime-info
          pip install --upgrade pip
          pip install buildozer cython==0.29.36 kivy
          yes | buildozer -v android debug
        env:
          FORCE_HEX_ENV: 1

      - name: Upload Game Package
        uses: actions/upload-artifact@v4
        with:
          name: brick-breaker-apk
          path: bin/*.apk
